name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7      
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api_yamdb/requirements.txt
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort

    - name: Check flake8 and pytest
      run: |
        python -m flake8
        # python -m pytest

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Check out the repo        
      uses: actions/checkout@v2 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1 
    - name: Login to Docker
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: margoloko/yamdb_final:latest
        file: api_yamdb/Dockerfile

  send_message:
    runs_on: ubuntu-latest
    #needs:
    steps:
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!
          